name: 'Update'

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'dist/**'

  schedule:
    # JST 4:00 AM
    - cron: '0 19 * * *'

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: 'go.sum'

      - name: Generate
        run: go run ./

      - name: Pull
        run: git pull

      - name: Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '🔄 Update'
